services:
  # Backend API Service
  - type: web
    name: talking-photo-backend
    runtime: python
    region: oregon
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GEMINI_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: FAL_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    healthCheckPath: /health

  # Frontend Service
  - type: web
    name: talking-photo-frontend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: REACT_APP_API_URL
        value: https://talking-photo-backend.onrender.com
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable

databases:
  # SQLite database will be in persistent disk
  # Note: Render free tier doesn't support persistent disk
  # Database will reset on each deploy
  # Consider upgrading to paid plan for persistent storage
