services:
  # Backend API Service
  - type: web
    name: talking-photo-backend
    runtime: python
    region: oregon
    plan: free
    buildCommand: ./build.sh
    startCommand: cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
      - key: GEMINI_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: FAL_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    healthCheckPath: /health

  # Frontend Service
  - type: static
    name: talking-photo-frontend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install --legacy-peer-deps && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: REACT_APP_API_URL
        value: https://talking-photo-backend.onrender.com

databases: []
  # SQLite database will be in persistent disk
  # Note: Render free tier doesn't support persistent disk
  # Database will reset on each deploy
  # Consider upgrading to paid plan for persistent storage
